### ISSUE TITLE
Open file with context manager

### ISSUE THREAD

**Issue by chillenzer** [edbennett/web-novice#21]
Hi,
small thing I noticed: You use 
```python3
ghtoken = open("github-access-token.txt",'r').read().strip()
```
which is nice and short but not very idiomatic. Although probably not urgently needed here, I think the context manager version is more idiomatic and fail-safe
```python3
with open("github-access-token.txt", "r") as file_handle:
    ghtoken = file_handle.read().strip()
```
What do you think?

**Comment by edbennett** [comment]
When I was writing this I thought "Should I use a context manager? But it takes two lines rather than one! I wonder if doing it on a single line automatically closes the context…"

And I seem to remember somehow confirming that the file handle did in fact get closed.

But that may be my memory playing tricks on me. If the context isn't correctly closed then we should definitely switch. Otherwise I'm ambivalent.

**Comment by chillenzer** [comment]
Okay. Looked it up. So, as you don't have any reference to the file after that line, it will get caught by the GarbageCollector at some point. It might be lurking around for a while but that is not too much of a problem as you only have read access. So, file integrity-wise it's is probably not an issue and resource usage is not really a concern here. The only arguments against that are un-idiomatic and error-prone (in the sense that you might use the same pattern for other access patterns, too). Still, strong arguments I think, particularly for a course someone might later use to actually copy over some production code. I am still advocating for changing this.

**Comment by edbennett** [comment]
I wish there were an idiom to make this neater, but that may be my code golf habit speaking.

Feel free to PR.

**Comment by mmesiti** [comment]
Coming back from the land of the dead for a moment (I was summoned by the mail notifications): I wrote that line. The reason why I did not use a context manager was that I intended this lesson to be more of a "hacking guide" than best practice guide. 
If I need to do something quick and dirty using ipython (that's how I taught it when it was my turn)

There were also other worse abominations that Colin and Ed

**Comment by mmesiti** [comment]
Sorry, coming back for a moment from the land of the dead (and messing up with opening and closing issues, apparently)
I wrote that line, and I was also aware of the beauty of context managers.  Here, my idea for the lesson was to run everything in ipython, where it is best to use code that fits in one line, and the value is in getting results quicker.
In my (somewhat limited) experience I want to spend more time looking at the structure of the data that one gets, more than fixing memory safety issues, for which you can just `%save`  and close ipython - hopefully. When I want to convert my experiments into proper scripts, then I would use a context manager.

But if you want to run the lesson in another way, then of course this might be a little too hacky. 

Now getting back to the land of the dead, have fun!

**Comment by edbennett** [comment]
Always great to hear from the no-longer-with-us! (I hope Germany is treating you well!) I didn't even look at which episode that line had come from. I definitely remember doing the check for how that would behave—maybe when I reviewed your part of this lesson?

Personally I think that even if the lesson is designed to be taught at a REPL where one-liners are preferable, it's almost certain that people will copy and paste lines from the material to places that aren't one-liners, so wherever code is shown in a code block then it should be written with that in mind.

(A potential bonus would be that if someone has learned how to open a file "properly" with a context manager, then they don't see a slightly different second syntax and get distracted from the lesson flow trying to understand a slightly different file open syntax.)
