### ISSUE TITLE
get request example could use NASA instead of metoffice

### ISSUE THREAD

**Issue by mmesiti** [edbennett/web-novice#7]
For our audience it makes sense to introduce the metoffice api, but to keep things concise one could use the NASA api in the episode about python requests (reducing the amount of setup needed)

**Comment by mmesiti** [comment]
this would also make #5 irrelevant

**Comment by edbennett** [comment]
I don't know how long the Met Office key takes to arrive—one reason I chose NASA is because it generates the key instantly, so it doesn't need to be done as a setup step. Agree that reducing the number of API keys and reusing them could make things run more smoothly.

**Comment by edbennett** [comment]
@mmesiti Does 5627f95 resolve this?

**Comment by mmesiti** [comment]
I guess so.
